### ISSUE TITLE
User story: Links to social media

### ISSUE THREAD

**Issue by Dym077** [Dym077/my-to-do-list#17]
Links to social media<epic>

As a **site user** I can **access the site owners social media pages** so that **I can learn more about the different features available and access tutorials about how to use the app effectively**

**Acceptance Criteria**

**Tasks**
- [ ] Add link in footer to Facebook
- [ ] Add link in footer to X
- [ ] Add link in footer to Youtube
