### ISSUE TITLE
User story: Sign up

### ISSUE THREAD

**Issue by Dym077** [Dym077/my-to-do-list#21]
Sign up:<user story>

As a **new user** I can **sign up entering a username and password f choice** so that **I can create a unique user profile and access the full functionality of the site**

**Acceptance Criteria**
- AC 1: Given that the "Username input field" is toggled when the user is clicking on it then the user should be able to enter the hosen username successfully
- AC 2: Given that the "Password input field " is toggled when the user is clicking on it then the user should be able to enter the chosen password successfully
- AC 3: Given that the "Sign up button " is toggled when the user is clicking on it then the user should be able to save the chosen credentials and sign up successfully
- 
**Tasks**
- [ ] Create username input field
- [ ] Create password input field
- [ ] Create sign up button
#2
