### ISSUE TITLE
User story: Edit calendar

### ISSUE THREAD

**Issue by Dym077** [Dym077/my-to-do-list#26]
Edit calendar:<user story>

As a **user** I can **edit and view my calendar page in a clean and understandable way** so that **I can get an up-to-date visual representation of my goals and tasks**

**Acceptance Criteria**

**Tasks**
- [ ] Calendar board - weekly view
- [ ] Calendar board - monthly view
- [ ] Next week toggle
- [ ] Previous week toggle
#7
