### ISSUE TITLE
User story: Responsiveness and accessibility

### ISSUE THREAD

**Issue by Dym077** [Dym077/my-to-do-list#33]
Responsiveness and accessibility:<user story>

As a **user** I can **expect that the site is responsive and accessible on all devices** so that **I can manage my goals and tasks anywhere, both on mobile, tablet, laptop and desktop.**
**Acceptance Criteria**
- AC 1: Given that the app is accessed by the user from any device then it is expected that the user will be able to navigate, manage the goals and tasks on the same device, ranging from mobile to desktop computer
 

**Tasks**
- [ ] Easy access and responsiveness on mobile device
- [ ] Easy access and responsiveness on tablet
- [ ] Easy access and responsiveness on desktop computer
- [ ] Easy access and responsiveness on laptop computer
#25
